CREATE TABLE tblS (
	SID SERIAL PRIMARY KEY,
	SValue VARCHAR(200) NOT NULL
);

CREATE TABLE tblP (
	PID SERIAL PRIMARY KEY,
	PValue VARCHAR(200) NOT NULL
);

CREATE TABLE tblUSER (
	UserID SERIAL PRIMARY KEY,
	PID INTEGER REFERENCES tblP(PID),
	SID INTEGER REFERENCES tblS(SID),
	UserFName VARCHAR(60) NOT NULL,
	UserLName VARCHAR(60) NOT NULL,
	UserEmail VARCHAR(60) NOT NULL,
	UserBirthDate DATE NOT NULL,
	UserGender VARCHAR(5) NOT NULL,
	FullAccount BIT(1) NOT NULL
);

CREATE TABLE tblEVENT (
	EventID SERIAL PRIMARY KEY,
	EventName VARCHAR(80) NOT NULL,
	EventDesc VARCHAR(500) NULL,
	EventStartDate DATE NOT NULL,
	EventEndDate DATE NOT NULL,
	EventLength INT NOT NULL,
	EventStartTime TIME NOT NULL,
	EventEndTime TIME NOT NULL,
	NotifyNumParticipant INT NOT NULL,
	NotifyDays INT NOT NULL,
	NotifyEachParticipant BIT(1) NOT NULL,
	EventUUID VARCHAR(100) NOT NULL
);

CREATE TABLE tblPREFERENCES (
	PreferenceID SERIAL PRIMARY KEY,
	PreferenceName VARCHAR(80) NOT NULL,
	PreferenceDesc VARCHAR(500) NULL
);

CREATE TABLE tblTIME (
	TimeID SERIAL PRIMARY KEY,
	UserID INTEGER REFERENCES tblUSER(UserID),
	EventID INTEGER REFERENCES tblEVENT(EventID),
	StartTime TIME NOT NULL,
	PreferenceID INTEGER REFERENCES tblPREFERENCES(PreferenceID)
);

--DUMMY DATA
INSERT INTO tblS (SValue)
VALUES('hello');

INSERT INTO tblP (PValue)
VALUES('abby');

INSERT INTO tblUSER (PID, SID, UserFName, UserLName, UserEmail, UserBirthDate, UserGender, FullAccount)
VALUES(1, 1, 'steven', 'raden', 'sraden@uw.edu', '6-11-1993', 'm', '1');