CREATE TABLE tblS (
	SID SERIAL PRIMARY KEY,
	SValue VARCHAR(200) NOT NULL
);

CREATE TABLE tblP (
	PID SERIAL PRIMARY KEY,
	--SID INTEGER REFERENCES tblS(SID),
	PValue VARCHAR(200) NOT NULL
);

CREATE TABLE tblUSER (
	UserID SERIAL PRIMARY KEY,
	PID INTEGER REFERENCES tblP(PID) NOT NULL,
	SID INTEGER REFERENCES tblS(SID) NOT NULL,
	UserFName VARCHAR(60) NOT NULL,
	UserLName VARCHAR(60) NOT NULL,
	UserEmail VARCHAR(60) NOT NULL,
	UserBirthDate DATE NOT NULL,
	UserGender VARCHAR(5) NOT NULL
);

CREATE TABLE tblEVENT (
	EventID SERIAL PRIMARY KEY,
	EventName VARCHAR(80) NOT NULL,
	EventDesc VARCHAR(500) NULL,
	EventStartDate DATE NOT NULL,
	EventEndDate DATE NOT NULL,
	EventLength INT NOT NULL
);

CREATE TABLE tblPREFERENCES {
	PreferenceID SERIAL PRIMARY KEY,
	PreferenceName VARCHAR(80) NOT NULL,
	PreferenceDesc VARCHAR(500) NULL
}

CREATE TABLE tblTIME (
	TimeID SERIAL PRIMARY KEY,
	UserID INTEGER REFERENCES tblUSER(UserID),
	EventID INTEGER REFERENCES tblEVENT(EventID),
	StartTime TIME NOT NULL,
	PreferenceID INTEGER REFERENCES tblPREFERENCES(PreferenceID)
);